// ============================================================
// Mock Data — Clinician Adoption Dashboard
// Metrics modeled on real Ambience Healthcare deployment data
// ============================================================

export const ACCOUNT = {
  name: "Midwest Regional Health System",
  totalClinicians: 172,
  totalTarget: 247,
  goLiveDate: "2025-09-15",
  currentPhase: "Phase 2 — Department Expansion",
  phases: [
    { name: "Phase 1 — Pilot", departments: ["fam-med", "internal-med"], status: "completed" },
    { name: "Phase 2 — Expansion", departments: ["cardiology", "orthopedics", "obgyn", "pediatrics"], status: "in_progress" },
    { name: "Phase 3 — Enterprise", departments: ["emergency", "surgery", "oncology", "psychiatry"], status: "planned" },
  ],
};

export const DEPARTMENTS = [
  {
    id: "fam-med",
    name: "Family Medicine",
    phase: 1,
    goLiveDate: "2025-09-15",
    totalClinicians: 42,
    activeClinicians: 39,
    utilizationRate: 0.88,
    avgTimeSavedPerWeek: 4.8,
    afterHoursReduction: 0.41,
    npsScore: 72,
    sameDayNoteClose: 0.81,
    wrvuChange: 0.04,
    status: "mature",
  },
  {
    id: "internal-med",
    name: "Internal Medicine",
    phase: 1,
    goLiveDate: "2025-09-15",
    totalClinicians: 38,
    activeClinicians: 31,
    utilizationRate: 0.72,
    avgTimeSavedPerWeek: 3.9,
    afterHoursReduction: 0.33,
    npsScore: 58,
    sameDayNoteClose: 0.68,
    wrvuChange: 0.02,
    status: "growing",
  },
  {
    id: "cardiology",
    name: "Cardiology",
    phase: 2,
    goLiveDate: "2025-11-01",
    totalClinicians: 28,
    activeClinicians: 14,
    utilizationRate: 0.45,
    avgTimeSavedPerWeek: 2.1,
    afterHoursReduction: 0.18,
    npsScore: 41,
    sameDayNoteClose: 0.52,
    wrvuChange: 0.01,
    status: "ramping",
  },
  {
    id: "orthopedics",
    name: "Orthopedics",
    phase: 2,
    goLiveDate: "2025-12-01",
    totalClinicians: 22,
    activeClinicians: 8,
    utilizationRate: 0.31,
    avgTimeSavedPerWeek: 1.2,
    afterHoursReduction: 0.09,
    npsScore: 34,
    sameDayNoteClose: 0.40,
    wrvuChange: -0.01,
    status: "at_risk",
  },
  {
    id: "obgyn",
    name: "OB/GYN",
    phase: 2,
    goLiveDate: "2026-01-15",
    totalClinicians: 18,
    activeClinicians: 3,
    utilizationRate: 0.12,
    avgTimeSavedPerWeek: 0.0,
    afterHoursReduction: 0.0,
    npsScore: null,
    sameDayNoteClose: null,
    wrvuChange: null,
    status: "onboarding",
  },
  {
    id: "pediatrics",
    name: "Pediatrics",
    phase: 2,
    goLiveDate: "2026-02-01",
    totalClinicians: 24,
    activeClinicians: 0,
    utilizationRate: 0.0,
    avgTimeSavedPerWeek: 0.0,
    afterHoursReduction: 0.0,
    npsScore: null,
    sameDayNoteClose: null,
    wrvuChange: null,
    status: "pre_launch",
  },
];

export const CLINICIANS = [
  // === Family Medicine (Phase 1 — Mature) ===
  {
    id: "c001",
    name: "Dr. Sarah Chen",
    department: "fam-med",
    role: "Physician",
    specialty: "Family Medicine",
    onboardDate: "2025-09-15",
    trainingStatus: "completed",
    utilizationRate: 0.95,
    utilizationTrend: "stable",
    encountersWithAmbience: 312,
    totalEncounters: 328,
    avgTimeSavedPerDay: 58,
    afterHoursMinutes: 12,
    npsResponse: 9,
    lastActive: "2026-02-05",
    championStatus: "champion",
    feedbackCount: 8,
    recentFeedback: "Love the HPI generation. Would like better surgical history capture.",
    riskLevel: "none",
    interventionNeeded: false,
  },
  {
    id: "c002",
    name: "Dr. James Rodriguez",
    department: "fam-med",
    role: "Physician",
    specialty: "Family Medicine",
    onboardDate: "2025-09-15",
    trainingStatus: "completed",
    utilizationRate: 0.92,
    utilizationTrend: "increasing",
    encountersWithAmbience: 287,
    totalEncounters: 312,
    avgTimeSavedPerDay: 52,
    afterHoursMinutes: 18,
    npsResponse: 8,
    lastActive: "2026-02-05",
    championStatus: "potential",
    feedbackCount: 5,
    recentFeedback: "Colleagues keep asking me how to customize templates. Happy to help.",
    riskLevel: "none",
    interventionNeeded: false,
  },
  {
    id: "c003",
    name: "Dr. Emily Watson",
    department: "fam-med",
    role: "Physician",
    specialty: "Family Medicine",
    onboardDate: "2025-09-15",
    trainingStatus: "completed",
    utilizationRate: 0.89,
    utilizationTrend: "stable",
    encountersWithAmbience: 265,
    totalEncounters: 298,
    avgTimeSavedPerDay: 48,
    afterHoursMinutes: 15,
    npsResponse: 8,
    lastActive: "2026-02-04",
    championStatus: "neutral",
    feedbackCount: 3,
    recentFeedback: "Works well for routine visits.",
    riskLevel: "none",
    interventionNeeded: false,
  },
  {
    id: "c004",
    name: "NP Lisa Torres",
    department: "fam-med",
    role: "Nurse Practitioner",
    specialty: "Family Medicine",
    onboardDate: "2025-09-15",
    trainingStatus: "completed",
    utilizationRate: 0.78,
    utilizationTrend: "increasing",
    encountersWithAmbience: 198,
    totalEncounters: 254,
    avgTimeSavedPerDay: 38,
    afterHoursMinutes: 25,
    npsResponse: 7,
    lastActive: "2026-02-05",
    championStatus: "neutral",
    feedbackCount: 2,
    recentFeedback: "Getting more comfortable. Wish it handled well-child visits better.",
    riskLevel: "none",
    interventionNeeded: false,
  },

  // === Internal Medicine (Phase 1 — Growing, with one at-risk) ===
  {
    id: "c005",
    name: "Dr. Michael Park",
    department: "internal-med",
    role: "Physician",
    specialty: "Internal Medicine",
    onboardDate: "2025-09-15",
    trainingStatus: "completed",
    utilizationRate: 0.34,
    utilizationTrend: "declining",
    encountersWithAmbience: 45,
    totalEncounters: 132,
    avgTimeSavedPerDay: 8,
    afterHoursMinutes: 65,
    npsResponse: 4,
    lastActive: "2026-01-28",
    championStatus: "resistant",
    feedbackCount: 2,
    recentFeedback: "Notes don't capture my assessment style. Going back to manual.",
    riskLevel: "high",
    interventionNeeded: true,
  },
  {
    id: "c006",
    name: "Dr. Angela Freeman",
    department: "internal-med",
    role: "Physician",
    specialty: "Internal Medicine",
    onboardDate: "2025-09-15",
    trainingStatus: "completed",
    utilizationRate: 0.85,
    utilizationTrend: "stable",
    encountersWithAmbience: 245,
    totalEncounters: 288,
    avgTimeSavedPerDay: 50,
    afterHoursMinutes: 20,
    npsResponse: 9,
    lastActive: "2026-02-05",
    championStatus: "champion",
    feedbackCount: 7,
    recentFeedback: "The auto-coding suggestions are saving our billing team hours. Fantastic.",
    riskLevel: "none",
    interventionNeeded: false,
  },
  {
    id: "c007",
    name: "Dr. David Liu",
    department: "internal-med",
    role: "Physician",
    specialty: "Internal Medicine",
    onboardDate: "2025-09-15",
    trainingStatus: "completed",
    utilizationRate: 0.71,
    utilizationTrend: "stable",
    encountersWithAmbience: 189,
    totalEncounters: 266,
    avgTimeSavedPerDay: 40,
    afterHoursMinutes: 28,
    npsResponse: 7,
    lastActive: "2026-02-04",
    championStatus: "neutral",
    feedbackCount: 3,
    recentFeedback: "Solid tool. Occasionally miss some medication reconciliation details.",
    riskLevel: "low",
    interventionNeeded: false,
  },
  {
    id: "c008",
    name: "PA Mark Jensen",
    department: "internal-med",
    role: "Physician Assistant",
    specialty: "Internal Medicine",
    onboardDate: "2025-10-01",
    trainingStatus: "completed",
    utilizationRate: 0.62,
    utilizationTrend: "increasing",
    encountersWithAmbience: 141,
    totalEncounters: 227,
    avgTimeSavedPerDay: 32,
    afterHoursMinutes: 30,
    npsResponse: 6,
    lastActive: "2026-02-03",
    championStatus: "neutral",
    feedbackCount: 1,
    recentFeedback: "Starting to trust it more for follow-up notes.",
    riskLevel: "none",
    interventionNeeded: false,
  },

  // === Cardiology (Phase 2 — Ramping) ===
  {
    id: "c009",
    name: "Dr. Priya Sharma",
    department: "cardiology",
    role: "Physician",
    specialty: "Cardiology",
    onboardDate: "2025-11-01",
    trainingStatus: "completed",
    utilizationRate: 0.78,
    utilizationTrend: "increasing",
    encountersWithAmbience: 89,
    totalEncounters: 114,
    avgTimeSavedPerDay: 42,
    afterHoursMinutes: 22,
    npsResponse: 8,
    lastActive: "2026-02-04",
    championStatus: "potential",
    feedbackCount: 6,
    recentFeedback: "Works great for routine visits. Struggles with complex cath lab follow-ups.",
    riskLevel: "none",
    interventionNeeded: false,
  },
  {
    id: "c010",
    name: "Dr. William Hayes",
    department: "cardiology",
    role: "Physician",
    specialty: "Cardiology",
    onboardDate: "2025-11-01",
    trainingStatus: "completed",
    utilizationRate: 0.52,
    utilizationTrend: "stable",
    encountersWithAmbience: 56,
    totalEncounters: 108,
    avgTimeSavedPerDay: 25,
    afterHoursMinutes: 35,
    npsResponse: 6,
    lastActive: "2026-02-03",
    championStatus: "neutral",
    feedbackCount: 2,
    recentFeedback: "Decent for general cardiology. Need echo/stress test result integration.",
    riskLevel: "low",
    interventionNeeded: false,
  },
  {
    id: "c011",
    name: "NP Rachel Green",
    department: "cardiology",
    role: "Nurse Practitioner",
    specialty: "Cardiology",
    onboardDate: "2025-11-15",
    trainingStatus: "completed",
    utilizationRate: 0.41,
    utilizationTrend: "increasing",
    encountersWithAmbience: 32,
    totalEncounters: 78,
    avgTimeSavedPerDay: 18,
    afterHoursMinutes: 40,
    npsResponse: 5,
    lastActive: "2026-02-02",
    championStatus: "neutral",
    feedbackCount: 1,
    recentFeedback: "Still learning the workflow. Training was helpful.",
    riskLevel: "none",
    interventionNeeded: false,
  },

  // === Orthopedics (Phase 2 — At Risk) ===
  {
    id: "c012",
    name: "Dr. Robert Kim",
    department: "orthopedics",
    role: "Physician",
    specialty: "Orthopedic Surgery",
    onboardDate: "2025-12-01",
    trainingStatus: "completed",
    utilizationRate: 0.15,
    utilizationTrend: "declining",
    encountersWithAmbience: 12,
    totalEncounters: 80,
    avgTimeSavedPerDay: 3,
    afterHoursMinutes: 70,
    npsResponse: 3,
    lastActive: "2026-01-15",
    championStatus: "disengaged",
    feedbackCount: 1,
    recentFeedback: "Doesn't understand surgical terminology well enough.",
    riskLevel: "high",
    interventionNeeded: true,
  },
  {
    id: "c013",
    name: "Dr. Karen Mitchell",
    department: "orthopedics",
    role: "Physician",
    specialty: "Orthopedic Surgery",
    onboardDate: "2025-12-01",
    trainingStatus: "completed",
    utilizationRate: 0.38,
    utilizationTrend: "stable",
    encountersWithAmbience: 28,
    totalEncounters: 74,
    avgTimeSavedPerDay: 12,
    afterHoursMinutes: 55,
    npsResponse: 5,
    lastActive: "2026-02-01",
    championStatus: "neutral",
    feedbackCount: 2,
    recentFeedback: "OK for post-op follow-ups but struggles with initial surgical consults.",
    riskLevel: "medium",
    interventionNeeded: true,
  },
  {
    id: "c014",
    name: "PA Tom Bradley",
    department: "orthopedics",
    role: "Physician Assistant",
    specialty: "Orthopedics",
    onboardDate: "2025-12-15",
    trainingStatus: "in_progress",
    utilizationRate: 0.22,
    utilizationTrend: "increasing",
    encountersWithAmbience: 15,
    totalEncounters: 68,
    avgTimeSavedPerDay: 6,
    afterHoursMinutes: 45,
    npsResponse: 5,
    lastActive: "2026-02-04",
    championStatus: "neutral",
    feedbackCount: 1,
    recentFeedback: "Just getting started. Seems promising for post-op notes.",
    riskLevel: "low",
    interventionNeeded: false,
  },

  // === OB/GYN (Phase 2 — Onboarding) ===
  {
    id: "c015",
    name: "Dr. Maria Santos",
    department: "obgyn",
    role: "Physician",
    specialty: "OB/GYN",
    onboardDate: "2026-01-15",
    trainingStatus: "in_progress",
    utilizationRate: 0.18,
    utilizationTrend: "increasing",
    encountersWithAmbience: 8,
    totalEncounters: 44,
    avgTimeSavedPerDay: 5,
    afterHoursMinutes: 50,
    npsResponse: null,
    lastActive: "2026-02-04",
    championStatus: "neutral",
    feedbackCount: 0,
    recentFeedback: null,
    riskLevel: "none",
    interventionNeeded: false,
  },
];

export const UTILIZATION_TRENDS = [
  { week: "Sep 22", famMed: 0.32, intMed: 0.28, cardiology: null, ortho: null },
  { week: "Oct 6", famMed: 0.48, intMed: 0.42, cardiology: null, ortho: null },
  { week: "Oct 20", famMed: 0.61, intMed: 0.52, cardiology: null, ortho: null },
  { week: "Nov 3", famMed: 0.70, intMed: 0.59, cardiology: 0.12, ortho: null },
  { week: "Nov 17", famMed: 0.74, intMed: 0.63, cardiology: 0.22, ortho: null },
  { week: "Dec 1", famMed: 0.78, intMed: 0.65, cardiology: 0.28, ortho: 0.10 },
  { week: "Dec 15", famMed: 0.82, intMed: 0.68, cardiology: 0.33, ortho: 0.18 },
  { week: "Dec 29", famMed: 0.84, intMed: 0.69, cardiology: 0.37, ortho: 0.25 },
  { week: "Jan 12", famMed: 0.85, intMed: 0.70, cardiology: 0.40, ortho: 0.28 },
  { week: "Jan 26", famMed: 0.87, intMed: 0.71, cardiology: 0.43, ortho: 0.30 },
  { week: "Feb 3", famMed: 0.88, intMed: 0.72, cardiology: 0.45, ortho: 0.31 },
];

export const FEEDBACK_LOG = [
  {
    id: "f001",
    clinicianId: "c005",
    date: "2026-01-28",
    type: "product",
    sentiment: "negative",
    text: "Notes don't capture my assessment style. Going back to manual.",
    category: "note_quality",
    actionTaken: null,
    priority: "high",
  },
  {
    id: "f002",
    clinicianId: "c001",
    date: "2026-02-03",
    type: "product",
    sentiment: "positive",
    text: "Love the HPI generation. Would like better surgical history capture.",
    category: "feature_request",
    actionTaken: "Submitted to product team",
    priority: "medium",
  },
  {
    id: "f003",
    clinicianId: "c012",
    date: "2026-01-14",
    type: "product",
    sentiment: "negative",
    text: "Doesn't understand surgical terminology well enough.",
    category: "note_quality",
    actionTaken: null,
    priority: "high",
  },
  {
    id: "f004",
    clinicianId: "c009",
    date: "2026-02-01",
    type: "product",
    sentiment: "positive",
    text: "Works great for routine visits. Struggles with complex cath lab follow-ups.",
    category: "feature_request",
    actionTaken: "Flagged for specialty template review",
    priority: "medium",
  },
  {
    id: "f005",
    clinicianId: "c002",
    date: "2026-01-30",
    type: "workflow",
    sentiment: "positive",
    text: "Colleagues keep asking me how to customize templates. Happy to help.",
    category: "peer_support",
    actionTaken: null,
    priority: "low",
  },
  {
    id: "f006",
    clinicianId: "c006",
    date: "2026-02-02",
    type: "praise",
    sentiment: "positive",
    text: "The auto-coding suggestions are saving our billing team hours. Fantastic.",
    category: "coding_accuracy",
    actionTaken: "Shared with product team as success story",
    priority: "low",
  },
  {
    id: "f007",
    clinicianId: "c013",
    date: "2026-01-25",
    type: "product",
    sentiment: "negative",
    text: "OK for post-op follow-ups but struggles with initial surgical consults.",
    category: "specialty_coverage",
    actionTaken: null,
    priority: "high",
  },
  {
    id: "f008",
    clinicianId: "c004",
    date: "2026-01-20",
    type: "training",
    sentiment: "neutral",
    text: "Getting more comfortable. Wish it handled well-child visits better.",
    category: "specialty_coverage",
    actionTaken: "Added to pediatric template backlog",
    priority: "medium",
  },
];

export const ALERTS = [
  {
    id: "a001",
    type: "utilization_drop",
    severity: "high",
    clinicianId: "c005",
    department: "internal-med",
    message: "Dr. Park's utilization dropped from 62% to 34% over 3 weeks",
    suggestedAction: "Schedule 1:1 workflow review. Review note template customization for assessment style.",
    createdDate: "2026-01-30",
    status: "open",
  },
  {
    id: "a002",
    type: "disengagement",
    severity: "high",
    clinicianId: "c012",
    department: "orthopedics",
    message: "Dr. Kim has not used Ambience in 21 days",
    suggestedAction: "Reach out with specialty-specific training. Connect with ortho champion from pilot site.",
    createdDate: "2026-02-02",
    status: "open",
  },
  {
    id: "a003",
    type: "champion_opportunity",
    severity: "info",
    clinicianId: "c002",
    department: "fam-med",
    message: "Dr. Rodriguez informally helping colleagues with templates — potential champion",
    suggestedAction: "Invite to Champion program. Offer advanced training and peer-teaching resources.",
    createdDate: "2026-02-01",
    status: "open",
  },
  {
    id: "a004",
    type: "department_risk",
    severity: "medium",
    clinicianId: null,
    department: "orthopedics",
    message: "Orthopedics utilization at 31%, below 60% target. Only 8 of 22 clinicians active.",
    suggestedAction: "Schedule department-level re-training. Address surgical terminology gaps flagged in feedback.",
    createdDate: "2026-02-03",
    status: "open",
  },
  {
    id: "a005",
    type: "utilization_drop",
    severity: "medium",
    clinicianId: "c013",
    department: "orthopedics",
    message: "Dr. Mitchell utilization plateaued at 38% — not progressing past initial adoption",
    suggestedAction: "Pair with Dr. Sharma (Cardiology) for cross-specialty peer session on complex notes.",
    createdDate: "2026-02-04",
    status: "open",
  },
];
